site_name: "JCC2018"
site_author: "Joint Cloud Computing Team"
site_description: "The 9th International Workshop on Joint Cloud Computing (JCC2018)"

nav:
- Home: index.md
- Intro: intro.md
- Program: program.md
- Call For Papers: cfp.md
- Organizers: organizers.md

copyright: "&#169; <a href='http://jointcloud.trustie.net'>JCC Team</a>"

repo_url: https://github.com/jointcloud/jcc2018.git

plugins:
    - search:
        separator: '[\s\-\.]+'

theme: 
  name: 'spacelab'
  custom_dir: spacelab

markdown_extensions:
 - admonition
    
extra:
      theme_inverse: true

extra_css:
  - css/custom.css

